// 🔒 SECURITY-CRITICAL (Step 5) — pending human security review; do NOT ship to a
// real user until reviewed. Uses vetted standard crypto.
package com.personalagent.shared.crypto

/**
 * The user-held recovery code: generation + canonical normalization.
 *
 * A code is [ENTROPY_BITS] bits of CSPRNG output rendered as RFC 4648 **Base32**
 * (A–Z, 2–7; all-caps, no padding) and grouped into 4-char blocks for legibility.
 * It carries **no checksum and no structure** —
 * the entire value is uniformly random, so it cannot be guessed or regenerated by
 * anyone (including the company). It is the single user-held secret of the recovery
 * path; see [RecoveryManager].
 */
object RecoveryCode {
    /**
     * Entropy of a generated code. 130 bits ≫ the 128-bit security of AES-256-GCM's
     * effective brute-force floor for this use, and is rendered as exactly 26 Base32
     * chars (130 / 5) → 7 dash-separated groups (`XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XX`).
     */
    const val ENTROPY_BITS = 130
    private const val SYMBOLS = ENTROPY_BITS / 5            // 26 base32 symbols
    private const val GROUP = 4
    private const val ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"  // RFC 4648 Base32

    /** Generate a fresh, grouped recovery code from [random] (must be a CSPRNG). */
    fun generate(random: SecureRandomBytes): String {
        // Draw enough random bytes to cover SYMBOLS*5 bits, then map 5 bits → 1 symbol.
        val bytesNeeded = (SYMBOLS * 5 + 7) / 8
        val bytes = random.nextBytes(bytesNeeded)
        val sb = StringBuilder(SYMBOLS + SYMBOLS / GROUP)
        var bitBuffer = 0
        var bitCount = 0
        var produced = 0
        var i = 0
        while (produced < SYMBOLS) {
            if (bitCount < 5) {
                bitBuffer = (bitBuffer shl 8) or (bytes[i++].toInt() and 0xFF)
                bitCount += 8
            }
            bitCount -= 5
            val idx = (bitBuffer ushr bitCount) and 0x1F
            if (produced > 0 && produced % GROUP == 0) sb.append('-')
            sb.append(ALPHABET[idx])
            produced++
        }
        return sb.toString()
    }

    /**
     * Canonicalize user input for KDF derivation: uppercase, then keep only the
     * characters that are in the Base32 alphabet — discarding dashes, spaces, and any
     * other formatting the user may type. Deliberately minimal and lossless w.r.t. the
     * alphabet (no confusable-remapping, which could silently disagree between wrap and
     * unwrap). The same normalized form is fed to the KDF at both wrap-time and
     * recovery-time, so the two MUST agree — keep this function the single source.
     */
    fun normalize(input: String): String {
        val sb = StringBuilder(input.length)
        for (raw in input) {
            val c = raw.uppercaseChar()
            if (c in ALPHABET) sb.append(c)
        }
        return sb.toString()
    }
}
