package com.personalagent.android.notification

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.getSystemService
import androidx.work.CoroutineWorker
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkManager
import androidx.work.WorkerParameters
import com.personalagent.android.MainActivity
import com.personalagent.android.PersonalAgentApp
import com.personalagent.shared.util.SystemClock
import java.util.concurrent.TimeUnit

/**
 * Phase 4 — gentle periodic reflection. A daily check decides whether a
 * reflection is *due* (per the user's weekly/monthly cadence, minus any snooze)
 * and, if so, posts ONE calm, low-key notification inviting a check-in. Tapping
 * opens the app. It never nags: at most one per cadence interval, and turning it
 * off (Off) cancels this worker entirely.
 *
 * The reflection *text* is generated by Hermes only when the user opens the
 * Reflection screen — we don't pre-fetch or store any content here.
 */
class ReflectionWorker(
    appContext: Context,
    params: WorkerParameters,
) : CoroutineWorker(appContext, params) {

    override suspend fun doWork(): Result {
        val app = applicationContext as? PersonalAgentApp ?: return Result.success()
        val store = app.container.reflectionStore
        val state = store.load()
        if (!state.isDue(SystemClock.nowMillis())) return Result.success()

        ReflectionNotifier.show(applicationContext)
        // Re-anchor so we don't notify again until the next interval (no nagging).
        store.markShown(SystemClock.nowMillis())
        return Result.success()
    }
}

/** Posts the gentle reflection nudge on its own channel (user can silence it). */
object ReflectionNotifier {
    const val CHANNEL_ID = "reflections"
    private const val CHANNEL_NAME = "Reflections"
    private const val NOTIF_ID = 88_001

    fun ensureChannel(context: Context) {
        val channel = NotificationChannel(
            CHANNEL_ID,
            CHANNEL_NAME,
            NotificationManager.IMPORTANCE_DEFAULT, // calm, not high-priority
        ).apply { description = "Gentle periodic check-ins from your Life Agent" }
        context.getSystemService<NotificationManager>()?.createNotificationChannel(channel)
    }

    fun show(context: Context) {
        ensureChannel(context)
        val open = Intent(context, MainActivity::class.java)
            .addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP)
        val pending = PendingIntent.getActivity(
            context, 0, open,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
        )
        val notification = NotificationCompat.Builder(context, CHANNEL_ID)
            .setSmallIcon(android.R.drawable.ic_menu_my_calendar)
            .setContentTitle("A moment to check in")
            .setContentText("Whenever you're ready — no pressure. Tap for a gentle reflection.")
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .setAutoCancel(true)
            .setContentIntent(pending)
            .build()
        val manager = NotificationManagerCompat.from(context)
        if (manager.areNotificationsEnabled()) {
            runCatching { manager.notify(NOTIF_ID, notification) }
        }
    }
}

/** Registers/cancels the daily reflection-due check. */
object ReflectionScheduling {
    private const val DAILY = "hermes_reflection_daily"

    /** Ensure the daily check runs (safe to call repeatedly). */
    fun ensureDaily(context: Context) {
        val req = PeriodicWorkRequestBuilder<ReflectionWorker>(1, TimeUnit.DAYS).build()
        WorkManager.getInstance(context)
            .enqueueUniquePeriodicWork(DAILY, ExistingPeriodicWorkPolicy.KEEP, req)
    }

    fun cancel(context: Context) {
        WorkManager.getInstance(context).cancelUniqueWork(DAILY)
    }
}
