import Foundation
import CryptoKit
import Security
import Shared

// 🔒🔒🔒 SECURITY-CRITICAL (Step 5 — encryption at rest, iOS) 🔒🔒🔒
//
// ⚠️ PENDING-REVIEW / NOT-FOR-REAL-USERS ⚠️
// This file MUST be reviewed by a second engineer and exercised on a real device
// (Secure Enclave + Keychain behavior) before it protects any real user data. It
// compiles-and-runs is NOT the bar; the Xcode build + on-device run is the gate.
//
// WHAT THIS IS
// The iOS implementation of the shared `IosNativeKeyStore` seam (see
// shared/iosMain `IosSecretKeyProvider.kt`). All cryptography uses Apple's vetted
// frameworks — we never roll our own:
//   • CryptoKit  — AES-256-GCM authenticated encryption of the data.
//   • Secure Enclave (P-256) — wraps (encrypts) the AES data key; its private key
//     is generated inside the Enclave and is non-exportable.
//   • Keychain  — stores the (Enclave-wrapped) data key blob and the Enclave key
//     reference, both `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`.
//
// HONEST SCOPE OF THE SECURE ENCLAVE'S ROLE
// AES-GCM itself runs on the CPU in this process's memory (that is how CryptoKit
// works — the Enclave cannot do arbitrary AES-GCM over app buffers). The Enclave's
// job here is to protect the *wrapping key*: the 256-bit AES data key is only ever
// stored ENCRYPTED to the Enclave's public key, and recovering it requires the
// Enclave to decrypt (the private key never leaves hardware). So at rest, neither
// the data nor the data key is recoverable without (a) the unlocked device and
// (b) that device's Enclave — or (c) the user's recovery code (below).
//
// FALLBACK: the Simulator and pre-A7 devices have no Secure Enclave
// (`SecureEnclave.isAvailable == false`). There we store the raw data key in the
// Keychain (still `WhenUnlockedThisDeviceOnly`), clearly tagged with a scheme
// byte. This keeps the Simulator (the build/verification gate) working; it is a
// weaker protection and is flagged as such.
final class IosSecretKeyStore: IosNativeKeyStore {

    // MARK: Identifiers
    private static let service = "com.personalagent.crypto"
    private static let dataKeyAccount = "data-key-v1"
    private static let enclaveKeyTag = "com.personalagent.crypto.enclave-key-v1".data(using: .utf8)!

    /// First byte of the stored data-key item: how the rest is protected.
    private static let schemeEnclaveWrapped: UInt8 = 0x01
    private static let schemeRawFallback: UInt8 = 0x02

    /// ECIES used to wrap/unwrap the data key with the Enclave P-256 key.
    private static let wrapAlgorithm: SecKeyAlgorithm =
        .eciesEncryptionCofactorVariableIVX963SHA256AESGCM

    /// The unwrapped AES data key, cached for this process lifetime once loaded.
    /// (It must be in-process for CryptoKit AES-GCM anyway.)
    private var cachedKey: SymmetricKey?

    enum KeyStoreError: Error {
        case alreadySetUp
        case noKey
        case enclaveUnavailable
        case wrapFailed(String)
        case unwrapFailed(String)
        case keychain(OSStatus)
        case invalidRecoveryCode
        case badCombinedBox
    }

    // MARK: - IosNativeKeyStore (the Kotlin-facing seam)

    func hasKey() -> Bool {
        return loadDataKeyItem() != nil
    }

    /// Idempotently create the device key if absent. Contract path used by
    /// `EncryptedKeyValueStorage`; does NOT surface a recovery code (the setup
    /// screen does that via `setUp()` before the store is first used).
    func ensureKey() throws {
        if hasKey() { return }
        _ = try generateAndStoreDataKey()
    }

    func encrypt(plaintext: KotlinByteArray, aad: KotlinByteArray) throws -> KotlinByteArray {
        let key = try dataKey()
        let sealed = try AES.GCM.seal(plaintext.toData(), using: key, authenticating: aad.toData())
        // `.combined` is `nonce(12) ‖ ciphertext ‖ tag(16)` — a fresh random nonce
        // is generated by `seal` on every call. Non-nil for the default 12-byte nonce.
        guard let combined = sealed.combined else { throw KeyStoreError.badCombinedBox }
        return combined.toKotlinByteArray()
    }

    func decrypt(ciphertext: KotlinByteArray, aad: KotlinByteArray) throws -> KotlinByteArray {
        let key = try dataKey()
        let box = try AES.GCM.SealedBox(combined: ciphertext.toData())
        // Throws `CryptoKitError.authenticationFailure` on wrong key / tamper / AAD
        // mismatch — never returns unverified plaintext.
        let plain = try AES.GCM.open(box, using: key, authenticating: aad.toData())
        return plain.toKotlinByteArray()
    }

    // MARK: - Swift-only API used by the first-run recovery setup screen

    /// First-run: generate the data key and return the user-held recovery code
    /// (a transcribable encoding of the 256-bit data key). Shown to the user ONCE
    /// for offline backup; there is intentionally no API to read it again, and it
    /// is never transmitted anywhere. Losing it AND the device = data is gone.
    /// Throws `.alreadySetUp` if a key already exists.
    func setUp() throws -> String {
        if hasKey() { throw KeyStoreError.alreadySetUp }
        let dataKeyData = try generateAndStoreDataKey()
        return RecoveryCode.encode(dataKeyData)
    }

    /// Restore on a new device by re-importing the data key from a recovery code,
    /// then re-wrapping it to THIS device's Secure Enclave. Used by the "I already
    /// have a recovery code" path on the setup screen.
    func restore(fromRecoveryCode code: String) throws {
        let dataKeyData = try RecoveryCode.decode(code)
        guard dataKeyData.count == 32 else { throw KeyStoreError.invalidRecoveryCode }
        try store(dataKeyData: dataKeyData)
    }

    /// Bridges to Bool for SwiftUI without importing the Kotlin name everywhere.
    var isSetUp: Bool { hasKey() }

    // MARK: - Data key lifecycle

    private func dataKey() throws -> SymmetricKey {
        if let cached = cachedKey { return cached }
        let key = try loadDataKey()
        cachedKey = key
        return key
    }

    /// Create a fresh random 256-bit AES key, store it (Enclave-wrapped or raw
    /// fallback), cache it, and return its raw bytes (for the recovery code).
    private func generateAndStoreDataKey() throws -> Data {
        let dataKeyData = SymmetricKey(size: .bits256).withUnsafeBytes { Data($0) }
        try store(dataKeyData: dataKeyData)
        return dataKeyData
    }

    /// Persist the given 32-byte data key, wrapping with the Secure Enclave where
    /// available, and update the in-memory cache.
    private func store(dataKeyData: Data) throws {
        let stored: Data
        if SecureEnclave.isAvailable {
            let priv = try enclavePrivateKey(createIfMissing: true)
            guard let pub = SecKeyCopyPublicKey(priv) else {
                throw KeyStoreError.wrapFailed("no public key")
            }
            guard SecKeyIsAlgorithmSupported(pub, .encrypt, Self.wrapAlgorithm) else {
                throw KeyStoreError.wrapFailed("algorithm unsupported")
            }
            var err: Unmanaged<CFError>?
            guard let wrapped = SecKeyCreateEncryptedData(
                pub, Self.wrapAlgorithm, dataKeyData as CFData, &err
            ) as Data? else {
                throw KeyStoreError.wrapFailed(Self.describe(err))
            }
            stored = Data([Self.schemeEnclaveWrapped]) + wrapped
        } else {
            // No Secure Enclave (Simulator / old device): store raw. FLAGGED weaker.
            stored = Data([Self.schemeRawFallback]) + dataKeyData
        }
        try keychainSetDataKeyItem(stored)
        cachedKey = SymmetricKey(data: dataKeyData)
    }

    private func loadDataKey() throws -> SymmetricKey {
        guard let stored = loadDataKeyItem(), let scheme = stored.first else {
            throw KeyStoreError.noKey
        }
        let body = stored.dropFirst()
        switch scheme {
        case Self.schemeEnclaveWrapped:
            let priv = try enclavePrivateKey(createIfMissing: false)
            var err: Unmanaged<CFError>?
            guard let raw = SecKeyCreateDecryptedData(
                priv, Self.wrapAlgorithm, Data(body) as CFData, &err
            ) as Data? else {
                throw KeyStoreError.unwrapFailed(Self.describe(err))
            }
            return SymmetricKey(data: raw)
        case Self.schemeRawFallback:
            return SymmetricKey(data: Data(body))
        default:
            throw KeyStoreError.unwrapFailed("unknown scheme \(scheme)")
        }
    }

    // MARK: - Secure Enclave P-256 wrapping key

    /// Load the Enclave-resident private key, optionally creating it. The private
    /// key is generated inside the Enclave and is non-exportable; only a reference
    /// to it is returned/stored.
    private func enclavePrivateKey(createIfMissing: Bool) throws -> SecKey {
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrApplicationTag as String: Self.enclaveKeyTag,
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecReturnRef as String: true,
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        if status == errSecSuccess, let key = item {
            return (key as! SecKey)
        }
        guard createIfMissing else { throw KeyStoreError.keychain(status) }
        guard SecureEnclave.isAvailable else { throw KeyStoreError.enclaveUnavailable }

        var acErr: Unmanaged<CFError>?
        guard let access = SecAccessControlCreateWithFlags(
            kCFAllocatorDefault,
            kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            [.privateKeyUsage],
            &acErr
        ) else {
            throw KeyStoreError.wrapFailed(Self.describe(acErr))
        }

        let attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeySizeInBits as String: 256,
            kSecAttrTokenID as String: kSecAttrTokenIDSecureEnclave,
            kSecPrivateKeyAttrs as String: [
                kSecAttrIsPermanent as String: true,
                kSecAttrApplicationTag as String: Self.enclaveKeyTag,
                kSecAttrAccessControl as String: access,
            ],
        ]
        var genErr: Unmanaged<CFError>?
        guard let priv = SecKeyCreateRandomKey(attributes as CFDictionary, &genErr) else {
            throw KeyStoreError.wrapFailed(Self.describe(genErr))
        }
        return priv
    }

    // MARK: - Keychain item for the (wrapped) data key

    private func loadDataKeyItem() -> Data? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: Self.service,
            kSecAttrAccount as String: Self.dataKeyAccount,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne,
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        guard status == errSecSuccess else { return nil }
        return item as? Data
    }

    private func keychainSetDataKeyItem(_ data: Data) throws {
        // Delete any prior item, then add fresh with the device-only protection.
        let base: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: Self.service,
            kSecAttrAccount as String: Self.dataKeyAccount,
        ]
        SecItemDelete(base as CFDictionary)

        var add = base
        add[kSecValueData as String] = data
        add[kSecAttrAccessible as String] = kSecAttrAccessibleWhenUnlockedThisDeviceOnly
        let status = SecItemAdd(add as CFDictionary, nil)
        guard status == errSecSuccess else { throw KeyStoreError.keychain(status) }
    }

    private static func describe(_ err: Unmanaged<CFError>?) -> String {
        guard let e = err?.takeRetainedValue() else { return "unknown error" }
        return (e as Error).localizedDescription
    }
}

// MARK: - KotlinByteArray <-> Data bridging

extension KotlinByteArray {
    func toData() -> Data {
        let n = Int(size)
        var data = Data(count: n)
        var i = 0
        while i < n {
            data[i] = UInt8(bitPattern: get(index: Int32(i)))
            i += 1
        }
        return data
    }
}

extension Data {
    func toKotlinByteArray() -> KotlinByteArray {
        let arr = KotlinByteArray(size: Int32(count))
        for (i, byte) in enumerated() {
            arr.set(index: Int32(i), value: Int8(bitPattern: byte))
        }
        return arr
    }
}

// MARK: - Recovery code encoding (NOT crypto — a transcribable encoding of the key)

/// Encodes the 32-byte data key as grouped uppercase hex so a human can write it
/// down and type it back. Decoding is lenient: it ignores spaces/dashes/case.
/// (Hex is used over a denser alphabet to keep the encode/decode obviously
/// correct; this is the user's offline backup, not a performance path.)
enum RecoveryCode {
    static func encode(_ data: Data) -> String {
        let hex = data.map { String(format: "%02X", $0) }.joined()
        // Group into blocks of 4 for legibility: "1A2B-3C4D-...".
        var groups: [String] = []
        var idx = hex.startIndex
        while idx < hex.endIndex {
            let end = hex.index(idx, offsetBy: 4, limitedBy: hex.endIndex) ?? hex.endIndex
            groups.append(String(hex[idx..<end]))
            idx = end
        }
        return groups.joined(separator: "-")
    }

    static func decode(_ code: String) throws -> Data {
        let cleaned = code.uppercased().filter { $0.isHexDigit }
        guard cleaned.count % 2 == 0 else { throw IosSecretKeyStore.KeyStoreError.invalidRecoveryCode }
        var data = Data()
        var idx = cleaned.startIndex
        while idx < cleaned.endIndex {
            let next = cleaned.index(idx, offsetBy: 2)
            guard let byte = UInt8(cleaned[idx..<next], radix: 16) else {
                throw IosSecretKeyStore.KeyStoreError.invalidRecoveryCode
            }
            data.append(byte)
            idx = next
        }
        return data
    }
}
